version: 2
jobs:
  go:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - run: ./internal/ci/init_gcloud
      - run: ./internal/ci/go_test
  gorace:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - run: ./internal/ci/gorace_test
  rust:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          key: cargo-cache
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - save_cache:
          key: cargo-cache
          paths:
              - ~/.cargo
      - run: ./internal/ci/rust_test
  sgx:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.12
    environment:
      SGX_ENABLED: yes
      # XXX: These are set in the base image but circleci seems to wipe them out
      PATH: "/root/.cargo/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sgxsdk/bin:/opt/sgxsdk/bin/x64"
      LD_LIBRARY_PATH: "/opt/sgxsdk/sdk_libs"
      SGX_SDK: "/opt/sgxsdk"
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - restore_cache:
          key: cargo-cache
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - save_cache:
          key: cargo-cache
          paths:
              - ~/.cargo
      - run: make chainlink
      - run: ./internal/ci/sgx_test
  geth:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -vendor-only
      - save_cache:
          name: Save Go Vendor Cache
          key: v1-go-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ./vendor
      - run: ./internal/ci/ethereum_test
  truffle:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
      - run: ./internal/ci/truffle_test
  gui:
    working_directory: /go/src/github.com/smartcontractkit/chainlink
    docker:
      - image: smartcontract/builder:1.0.12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn
      - run: ./internal/ci/init_gcloud
      - run: ./internal/ci/gui_test
  reportcoverage:
    docker:
      - image: smartcontract/builder:1.0.12
    steps:
      - checkout
      - run: ./internal/ci/init_gcloud
      - run: ./internal/ci/report_coverage
  deploy:
    docker:
      - image: smartcontract/deployer:latest
    environment:
      ENVIRONMENT: release
      DOCKER_TAG: staging
    steps:
      - checkout
      - run: ./internal/ci/init_gcloud
      - setup_remote_docker
      - run: echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run: make docker
      - run: make dockerpush
      - run: |
          docker inspect --format='{{index .RepoDigests 0}}' "smartcontract/chainlink:staging" \
            | awk -F'@' '{print$2}' \
            | xargs -I'%' kubectl set image deployment.apps/chainlink-deploy \
                "chainlink=smartcontract/chainlink:staging@%"


workflows:
  version: 2
  test:
    jobs:
      - go
      - gorace
      - truffle
      - geth
      - gui
      - rust
      - sgx
      - reportcoverage:
          requires:
            - go
            - gui
      - deploy:
          requires:
            - go
            - gorace
            - truffle
            - geth
            - gui
          filters:
            branches:
              only: master
